app:
  name: "test-app"
  image: "nginx"
  tag: "alpine3.17-slim"
spec:
  replicas: "2"
  resources:
    requests:
      memory: "50Mi"
      cpu: "20m"
    limits:
      memory: "500Mi"
      cpu: "200m"
  port: 80
